<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Updater.Core\Updater.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Image\background.png" Link="Image\background.png" />
  </ItemGroup>

</Project>
